// Mocks generated by Mockito 5.3.2 from annotations
// in mobii_exam_clean/test/src/data/repositories/user/user_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mobii_exam_clean/src/data/data_sources/user/user_data_source.dart'
    as _i2;
import 'package:mobii_exam_clean/src/data/models/user/user_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserDataSourceImpl extends _i1.Mock
    implements _i2.UserDataSourceImpl {
  MockUserDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.UserModel>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i3.Future<List<_i4.UserModel>>.value(<_i4.UserModel>[]),
      ) as _i3.Future<List<_i4.UserModel>>);
}
